Añadido endpoint de login y funciones en models
kholostyak17/braulg pull request #19
Opened 2021-06-07 16:02 UTC by scsanchez

Añadido endpoint de login y funciones en models.

2021-06-07 16:10 UTC, kholostyak17 approved these changes

2021-06-08 09:10 UTC, scsanchez commented
Añadido el post de registro con filtración si el email ya está.

2021-06-08 12:45 UTC, JimenaEB requested changes

2021-06-08 12:45 UTC, JimenaEB commented on src/api/models.py
> +
No entiendo que queréis hacer aquí

2021-06-08 12:45 UTC, JimenaEB commented on src/api/models.py
> +
Esto tampoco va a funcionar

2021-06-08 12:45 UTC, JimenaEB commented on src/api/routes.py
> +            if traveler.validate_password(password):
podemos simplificar la cantidad de ifs y para validar no os sirve esa funcion

2021-06-08 12:45 UTC, JimenaEB commented on src/api/routes.py
> +                traveler_with_token = traveler.traveler_with_token(access_token)
Tampoco es necesario esto

2021-06-08 12:45 UTC, JimenaEB commented on src/api/routes.py
> +              return ({'error':"Traveler already exist"}),201
Primero comprobad que los campos obligatorios estén y luego comprobamos que exista, pero igual, nos podemos ahorrar ifs

2021-06-08 12:45 UTC, JimenaEB commented on src/api/routes.py
> +            new_traveler = Traveler(name=name,email=email, _password=password, language=language, age=age)
Hay que guardar la contraseña encriptada

2021-06-08 12:45 UTC, JimenaEB commented on src/api/routes.py
> +            password = generate_password_hash(password, method='pbkdf2:sha256')
Esto va antes del usuario creado

2021-06-08 12:45 UTC, JimenaEB commented on src/api/routes.py
> +
aquí en vez de if else usemos las exceociones y hagamos un try carch

2021-06-08 14:34 UTC, Diego-EC approved these changes

2021-06-10 14:46 UTC, kholostyak17 approved these changes

2021-06-10 15:07 UTC, Diego-EC approved these changes

2021-06-10 15:36 UTC, merged