Feature/andrea/vista del blog
kholostyak17/braulg pull request #21
Opened 2021-06-08 08:34 UTC by Andreagar28

Vistas "trip proposal"
"trip proposal id"

2021-06-08 12:46 UTC, JimenaEB commented
Soluciona primero los conflictos con master mergeando en tu rama la rama master

2021-06-08 14:30 UTC, Diego-EC requested changes

2021-06-08 14:30 UTC, Diego-EC commented on src/front/js/component/TripProposal.js
> +const TripProposal = props => {
El nombre del componente está bien, pero el del fichero no cumple con la nomenclatura. Separa las palabras con '-'

2021-06-08 14:30 UTC, Diego-EC commented on src/front/js/component/TripProposalId.js
> +	const { store, actions } = useContext(Context);
El del fichero no cumple con la nomenclatura. Separa las palabras con '-'
Además, el nombre del componente no es descriptivo. ¿Qué significa TripProposalId?

2021-06-08 14:30 UTC, Diego-EC commented on src/front/js/component/cardblog.js
>  const CardBlog = props => {
el nombre del fichero sería card-blog. El nombre del componente está bien.

2021-06-08 14:30 UTC, Diego-EC commented on src/front/js/component/TripProposalId.js
> +			<br />
El <br /> mejor cámbialo por un margen en CSS o con una clase de bootstrap (por ejemplo mb-* de marging bottom). De esta forma no utilizamos HTML para el estilo de la página.

2021-06-08 14:30 UTC, Diego-EC commented on src/front/js/component/TripProposal.js
> +import person1 from "./personasImg/imgperson1.jpeg";
**Esto está muy bien**, es una buena practica poner las rutas relativas de las imágenes importadas al principio del fichero en lugar de dentro del componente o tag que las usa 👍👍👍

2021-06-08 14:30 UTC, Diego-EC commented on src/front/styles/card-blog.scss
> +.titleForest{
Los nombres deben ser descriptivos y hacer referencia a la funcionalidad, no al color. Toma como ejemplo los nombres de las clases de bootstrap (btn-primary, btn-warning, ...)

2021-06-08 14:30 UTC, Diego-EC commented on src/front/styles/card-blog.scss
> +    width:90%;
sangra (o indenta) bien todos los bloques de código, tienes varios bloques de código mal sangrados en este fichero.

2021-06-08 14:30 UTC, Diego-EC commented on src/front/styles/trip-proposal.scss
> +.infoText{
sangra (o indenta) bien todos los bloques de código, tienes varios bloques de código mal sangrados en este fichero.

2021-06-08 14:30 UTC, Diego-EC commented on src/front/styles/trip-proposal-id.scss
> +width: 301.69px;
sangra (o indenta) bien todos los bloques de código, tienes varios bloques de código mal sangrados en este fichero.

2021-06-09 10:41 UTC, Andreagar28 commented
Corregido

2021-06-10 15:28 UTC, JimenaEB commented
Arreglas primero de todo los cambios con main

2021-06-11 08:04 UTC, Diego-EC requested changes

2021-06-11 08:04 UTC, Diego-EC commented on src/front/js/component/cardblog.js
> +export const Card_Blog = props => {
El nombre del componente, no es Card_Blog, sino CardBlog ;)

2021-06-11 08:04 UTC, Diego-EC commented on src/front/js/component/cardblog.js
> +import React, { useContext, useEffect, Fragment } from "react";
el fichero no es cardblog, sino card-blog ;)

2021-06-11 08:04 UTC, Diego-EC commented on src/front/js/pages/Jaques-Chat.js
> +import React from "react";
no pongas mayúsculas en el nombre del fichero

2021-06-11 08:04 UTC, Diego-EC commented on src/front/js/pages/Jaques-Chat.js
> +export const Jaques_Chat = () => {
el nombre del componente, ponlo sin sin '_'

2021-06-11 08:04 UTC, Diego-EC commented on src/front/js/store/flux.js
> +			getPosts: () => {
están muy bien estos nombres de métodos 👍👏

2021-06-11 08:04 UTC, Diego-EC commented on src/front/styles/trip-card.scss
> +    font-size: 64px;
has puesto valores en pixeles en todos sitios, no te voy a pedir que los cambies, pero no es una buena practica; solo tenlo en cuenta para cosas nuevas que hagas el resto del proyecto

2021-06-11 08:04 UTC, Diego-EC commented on src/front/js/pages/trip-details.js
> +			<h1 className="tripProposalTitleId">Trip (id0001)</h1>
Entiendo que este texto 'Trip (id0001)', ¿lo tienes así porque todavía no estás recuperando los trips de backend?

2021-06-11 08:04 UTC, Diego-EC commented on src/front/styles/chat.scss
> +    font-family: Roboto;
parametrizar las tipografías

2021-06-15 13:01 UTC, closed without merging