faqs
kholostyak17/braulg pull request #29
Opened 2021-06-14 18:08 UTC by Andreagar28

Preguntas Frecuentes

2021-06-15 13:03 UTC, JimenaEB requested changes

2021-06-15 13:03 UTC, JimenaEB commented on src/front/js/pages/home_copy.js
> +import { Context } from "../store/appContext";
Este fichero creo que no hace falta

2021-06-15 13:03 UTC, JimenaEB commented on src/front/styles/faq.scss
> +}
No uses important! por fi 😱 😭

2021-06-15 13:03 UTC, JimenaEB commented on src/front/js/pages/faq.js
> +								<br />
No uses <br> que queda muy feo, mejor usar margin y darle una clase CSS a los parrafos

2021-06-15 22:50 UTC, Andreagar28 commented
Ya he realizado los cambios requeridos. Gracias.

2021-06-16 14:43 UTC, JimenaEB approved these changes

2021-06-16 16:23 UTC, merged