BBDD: Arreglado Shared_trip en rutas. Perfil: Cartas por usuario
kholostyak17/braulg pull request #41
Opened 2021-06-28 13:13 UTC by scsanchez

2021-06-28 21:26 UTC, kholostyak17 commented on src/front/js/component/trip-profile-card.js
> +					const linkToPartnerID = "../user/".concat(partner.id);
en los tag <Link> no poner puntos delante de la barra en la ruta, ejemplo:
"../user" -> mal
"/user/" -> bien

2021-06-28 21:26 UTC, kholostyak17 commented on src/front/js/component/trip-profile-card.js
> +			setPartnersMap(<p>Todavía nadie se ha unido nadie</p>);
"nadie" esta repetido

2021-06-28 21:32 UTC, kholostyak17 commented on src/front/js/pages/settings.js
> +	useEffect(() => {
aquí en la vista de settings ya se había solucionado el problema de que a veces cargaban los datos y otras veces no,
mediante la llamada a una función en el actions getUser y guardando los datos en la variable currentUser del store.
Tal vez tienes una versión desactualizada, en algún momento podemos hacer juntos un pull desde master para solucionar conflictos

2021-06-28 21:37 UTC, kholostyak17 requested changes
esta muy bien todo sergio!!!!
solamente faltaría hacer un pull desde master antes de mergear porque creo que esta rama esta 18 commits desactualizada respecto a la principal, mañana lo podemos hacer juntos por la mañana.

2021-06-28 22:34 UTC, scsanchez commented on src/front/js/component/trip-profile-card.js
> +					const linkToPartnerID = "../user/".concat(partner.id);
Me lo apunto, estuve probando con ./user/ y ../user/ pero creo que ninguna funcionaba

2021-06-28 22:37 UTC, scsanchez commented on src/front/js/component/trip-profile-card.js
> +			setPartnersMap(<p>Todavía nadie se ha unido nadie</p>);
Arreglado!

2021-06-29 15:39 UTC, kholostyak17 approved these changes

2021-06-29 15:40 UTC, merged